version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      # - DB_HOST=${DB_HOST}
      # - DB_PORT=${DB_PORT}
      # - DB_USER=${DB_USER}
      # - DB_PASS=${DB_PASS}
      # - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
